
mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql

#server:
  
spring:
  application:
    name: beecomb-worker
  profiles:
    include: shardingsphere    

commons:
  mybatis:
    mapperScan:
      basePackages: io.github.icodegarden.beecomb.common.backend.mapper

