
mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql

server:
  bindIp: localhost #工作环境的局域网自动ip无法访问
  
spring:
  application:
    name: beecomb-worker
  profiles:
    include: shardingsphere,shardingsphere-config 

icodegarden:
  nursery:
    mybatis:
      mapperScan:
        basePackages: io.github.icodegarden.beecomb.common.backend.mapper

