
mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql

#server:
  #生产环境只关注大于该值的sql
#  sqlUnhealthMillis: 150
  
spring:
  application:
    name: beecomb-worker
  profiles:
    include: shardingsphere    



