#management.server.address: 127.0.0.1
management.server.port: 9897
#management.endpoint.shutdown.enabled: true
management.endpoints.web.exposure.include: health,readiness

mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: false
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql


server:
  port: 9898
  
spring:
  application:
    name: beecomb-master
  profiles:
    include: shardingsphere,shardingsphere-config
  mvc.servlet.load-on-startup: 1  
  #关闭thymeleaf的缓存
  thymeleaf:
    cache: false
  

icodegarden:
  nursery:
    web:
      exceptionHandler:
        apiResponse:
          enabled: false
        nativeRestApi:
          enabled: true
    mybatis:
      mapperScan:
        basePackages: io.github.icodegarden.beecomb.common.backend.mapper,io.github.icodegarden.beecomb.master.mapper
    endpoint:
      readiness:
        enabled: true  
  