
mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: false
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql


server:
  port: 9898
  #生产环境只关注大于该值的sql
#  sqlUnhealthMillis: 150
  
spring:
  application:
    name: beecomb-master
  profiles:
    include: shardingsphere
  mvc.servlet.load-on-startup: 1  
  #关闭thymeleaf的缓存
  thymeleaf:
    cache: false
#  datasource:
#    url: jdbc:mysql://192.168.80.128:3306/beecomb_0?setUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20
##      max-lifetime: 1800000
##      idle-timeout: 600000
##      connection-timeout: 3000
##      connection-test-query: SELECT 1  
  
