
mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: false
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql


server:
  port: 9898
  #生产环境只关注大于该值的sql
#  sqlUnhealthMillis: 150
  
spring:
  application:
    name: beecomb-master
  profiles:
    include: shardingsphere
  mvc.servlet.load-on-startup: 1  
  #关闭thymeleaf的缓存
  thymeleaf:
    cache: false
  

commons:
  mybatis:
    mapperScan:
      basePackages: io.github.icodegarden.beecomb.common.backend.mapper,io.github.icodegarden.beecomb.master.mapper
  endpoint:
    readiness:
      enabled: true  
  